###frontend - k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-frontend
  template:
    metadata:
      labels:
        app: whatsapp-frontend
    spec:
      containers:
        - name: whatsapp-frontend
          image: 713916818035.dkr.ecr.ap-south-1.amazonaws.com/whatsapp-frontend-ey:latest
          ports:
            - containerPort: 8080


